services:
  test1:
    build:
      context: .
    image: alpha
    container_name: test1
    ports:
      - "5001:5000"
    environment:
      - FLASK_ENV=production
    volumes:
      - ./ui/templates:/app/ui/templates
    restart: unless-stopped
  test2:
    build:
      context: .
    image: alpha
    container_name: test2
    ports:
      - "5002:5000"
    environment:
      - FLASK_ENV=production
    volumes:
      - ./ui/templates:/app/ui/templates
    restart: unless-stopped
